pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/yourname/alx-backend-python.git'
        APP_DIR = 'messaging_app'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        DOCKER_IMAGE = 'yourdockername/messaging_app'
    }

    stages {

        stage('Clone Repo') {
            steps {
                git(
                    url: "${REPO_URL}",
                    branch: 'main',
                    credentialsId: 'github-creds'
                )
            }
        }

        stage('Create Virtual Env & Install Deps') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                        pip install pytest pytest-django pytest-cov
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        . venv/bin/activate
                        pytest --maxfail=1 --disable-warnings \
                        --junitxml=test-report.xml
                    '''
                }
            }
            post {
                always {
                    junit "${APP_DIR}/test-report.xml"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh """
                        docker build -t ${DOCKER_IMAGE}:latest .
                    """
                }
            }
        }

        stage('Login & Push Docker Image') {
            steps {
                sh """
                    echo '${DOCKERHUB_CREDENTIALS_PSW}' | docker login -u '${DOCKERHUB_CREDENTIALS_USR}' --password-stdin
                    docker push ${DOCKER_IMAGE}:latest
                """
            }
        }
    }

    triggers {
        pollSCM('')
    }
}
