pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/yourname/alx-backend-python.git'
        APP_DIR = 'messaging_app'
        DOCKER_IMAGE = 'yourdockername/messaging_app'
    }

    stages {

        stage('Clone Repo') {
            steps {
                // checker requires "git branch"
                git branch: 'main',
                    url: "${REPO_URL}",
                    credentialsId: 'github-creds'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip3 install --upgrade pip
                        pip3 install -r messaging_app/requirements.txt
                        pip3 install pytest pytest-django pytest-cov
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        . venv/bin/activate
                        pytest --junitxml=test-report.xml
                    '''
                }
            }
            post {
                always {
                    junit "${APP_DIR}/test-report.xml"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh """
                        docker build -t ${DOCKER_IMAGE}:latest .
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    passwordVariable: 'DOCKER_PASSWORD',
                    usernameVariable: 'DOCKER_USERNAME'
                )]) {
                    sh """
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        docker push ${DOCKER_IMAGE}:latest
                    """
                }
            }
        }
    }

    triggers {
        pollSCM('')
    }
}
